@startuml Architecture Overview


package Application {
    class GPIO
    class App
}

package Core {
   class HAL
   class OS {
    + void setup()
    + void loop()
   }
   class FreeRTOS
   class STM32F407_HAL

   OS --> FreeRTOS
   HAL --> STM32F407_HAL
}

GPIO --> HAL
App --> GPIO
App --> OS
@enduml